#! /usr/bin/env bash
# 'bundle install' fails when the path of the current working directory path
# contains spaces. solution: run bundle install in tmpdir, then copy back the
# '.direnv'
FULL_PATH=$(realpath .)
BASE_NAME=$(basename "$FULL_PATH")
cd $(realpath "$(mktemp -d)")
cp -r "$FULL_PATH" .
cd "$BASE_NAME"
direnv allow . && eval "$(direnv export bash)"
bundle install
cd ..
mv "$BASE_NAME"/.direnv "$FULL_PATH"/.direnv
