defaults:
  - scope:
      path: "assets/minutes"
    values:
      minutes: true
collections:
  - boxes
permalink: /:year-:month-:day-:title:output_ext
plugins:
  - jekyll-feed
title: "Scandinavian Logic Society" # for feeds
feed:
  categories:
    - events
    - positions
