defaults:
  - scope:
      path: "assets/minutes"
    values:
      minutes: true
permalink: /:year-:month-:day-:title:output_ext
plugins:
  - jekyll-feed
  - jekyll-redirect-from
title: "Scandinavian Logic Society" # for feeds
feed:
  categories:
    - events
    - positions
future: true
exclude:
  - "TODO.md"
